### PR TITLE
Fix su: build it properly from meson, print error messages leading with actual binary name rather than just 'su'

### PR DESCRIPTION
**Pull request by moon-chilled**

### CODE REVIEW

**Comment by Member1221** [comment]
Don't know why it matters to fetch the app name from the args, like it's the su application specifically.

**Comment by moon-chilled** [comment]
That's the way it's done.  It's not necessarily to do with a different binary name—though it could be—but generally showing the command exactly the way you specify it.  E.G. see the difference between `cat nonexistent_file` and `/bin/cat nonexistent_file`.

**Comment by chaomodus** [comment]
I'm generally in favor of that sort of change.

**Comment by chaomodus** [comment]
Just a note this has been superceded by changes, for one thing su now uses the new command line parser, and for another I've commited changes based on this (and more) to the meson.build so that deps get used correctly.

**Comment by chaomodus** [comment]
(btw thanks for being involved! not to denigrate this work, i think it has set me on a good path)

**Pull request closed without merging**
